Disc 791/rewrite result item to vue
kb-dk/ds-web pull request #120
Opened 2024-02-14 12:13 UTC by jorntx

Complete rewrite wi-result-item from web component to Vue component.

Had to adjust wc-image-item along the way due to the need for open shadow DOM in order for it to work directly in the new Vue component (ResultItem).

2024-02-19 13:41 UTC, jesperlauridsen commented on src/components/search/wc-result-item.ts
> -	private updateSkeletonDifferences() {
This part seems to have been omitted from the refactor. This made the skeletons have different lengths, so they looked "different". Both the spans and the titles. This probably needs to be rebuild with Vue tech instead of this way to do it.

2024-02-19 13:45 UTC, jesperlauridsen requested changes
All looks good, apart from the missing skeleton sizes. Update that and it's good to go! \o/

2024-02-21 07:16 UTC, jorntx commented on src/components/search/wc-result-item.ts
> -	private updateSkeletonDifferences() {
I gave it a stab. Check it out and see if it is OK.

2024-02-26 22:19 UTC, jesperlauridsen commented
This is super close to what is was before we remade the component. There was a little padding between the skeleton bars, but I think we can just ignore this for now and fix that when doing animations. Good job from my end - just some merge conflicts and we're good to go!

2024-02-26 22:19 UTC, jesperlauridsen approved these changes

2024-02-27 10:33 UTC, jorntx commented
Ready for merge @jesperlauridsen !

2024-02-27 12:23 UTC, merged