DRA-461 show pages in top of search results
kb-dk/ds-web pull request #155
Opened 2024-04-18 13:07 UTC by jesperlauridsen

Not much to it.

2024-04-19 08:32 UTC, jorntx requested changes
Nice simple implementation. A couple of minor comments and one bug:

When loading the count shows 1/0 on page one and 2/0 on page two etc. - see attached screenie.
<img width="121" alt="Screenshot 2024-04-19 at 10 22 22" src="https://github.com/kb-dk/ds-web/assets/1721001/6682d9fa-3e93-4d38-8bc2-035e2342ca26">

Can be reproduced by searching for * and if you have search result you can step to page 2 and try to reload.

2024-04-19 08:32 UTC, jorntx commented on src/components/search/SearchOverhead.vue
> +					</div>
Good simple implementation that works calculation wise. If the logic gets slightly more complicated you could consider moving it to functions in setup()

2024-04-19 08:32 UTC, jorntx commented on src/components/search/SearchOverhead.vue
> +	//color: #000000;
You need to use asterisk `/*`  when commenting out in css:)

2024-04-19 09:24 UTC, jesperlauridsen commented
> Nice simple implementation. A couple of minor comments and one bug:
> 
> When loading the count shows 1/0 on page one and 2/0 on page two etc. - see attached screenie. <img alt="Screenshot 2024-04-19 at 10 22 22" width="121" src="https://private-user-images.githubusercontent.com/1721001/323889038-6682d9fa-3e93-4d38-8bc2-035e2342ca26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTg1NTMsIm5iZiI6MTcxMzUxODI1MywicGF0aCI6Ii8xNzIxMDAxLzMyMzg4OTAzOC02NjgyZDlmYS0zZTkzLTRkMzgtOGJjMi0wMzVlMjM0MmNhMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDkxNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzU5YThkNmI4MjYwM2QyNGYwYTZjYWRjYzA2ZDIyMTIwOTE5NWIxZTZjZGMzMGJmNzQ5ZTM1ODk1NDA0MGViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CnqfdViTnmYIE3AgCJxcOfUu361NmLyVEx7WCdQ3ha4">
> 
> Can be reproduced by searching for * and if you have search result you can step to page 2 and try to reload.

That's a booboo! I'm sorry, fixed now!

2024-04-22 07:36 UTC, jorntx approved these changes
Thanks for the changes. Looks good and works as intended.

2024-04-22 07:37 UTC, merged