Dra 1349 no result page
kb-dk/ds-web pull request #210
Opened 2024-10-31 13:26 UTC by Pbruun

Displays all the suggestions for the search. 
Got some advice for a better search

2024-11-05 13:29 UTC, jesperlauridsen commented on src/components/global/content-elements/TextAndImage.vue
> +		width: 80%;
Why 80%? This makes it not centeret on a small screen, which seems a little odd?

2024-11-05 13:30 UTC, jesperlauridsen commented on src/locales/en.json
> +        "link": ""
We need to remember this some way - Maybe add a JIRA tastk to get this updated before launch?

2024-11-05 13:32 UTC, jesperlauridsen requested changes
This seems very good! I have a few comments, but other than that i got nothing for the code. I got a few concerns about the design, but those do not belong here. Gj, have a look at the 2 comments i left, and when you're good to go I'll merge this \o/

2024-11-05 13:47 UTC, jesperlauridsen commented
Also, 
![image](https://github.com/user-attachments/assets/9b639b59-f40a-4178-9056-6d6754a98681)
If you do a combination of a search, and some selections, in this case http://localhost:3000/find-materiale/dr-arkivet/find?q=bl%C3%A5&start=0&sort=score+desc&fq=creator_affiliation_facet%253A%2522DR%2520P3%2522&fq=genre%253A%2522Videnskab%2520og%2520natur%2522

 a saerch on "blå", and a selected creator (DR P3) and a genre (videnskab og natur), you get nothing - but the "mente du" shows up, but its empty. That should either contain something, or not be present, no?

2024-11-05 20:03 UTC, Pbruun commented on src/components/global/content-elements/TextAndImage.vue
> +		width: 80%;
I made it 80%, because i thought the line breaks seemed a bit odd. 
Changed to 100% so it is center.

2024-11-06 08:52 UTC, Pbruun commented
Link to "search tips" is now correct on the danish page. English version will be made later today. 
We had multiple spellings of "DR-archive" UX asked for it to be made similar.

2024-11-06 09:53 UTC, merged