DRA-Optional: New calendar look
kb-dk/ds-web pull request #264
Opened 2024-12-12 13:56 UTC by jesperlauridsen

This is a draft-branch for the new calendar functionality. Not to be merged untill it's ready and approved.

2025-01-06 09:42 UTC, Pbruun commented
Awesome! The look and functionality works great. Just find it a bit aggressive with the pop-ups, whenever changing the date in the input. Maybe a timer, if the input remains incorrect, then a pop-up?

2025-01-06 09:48 UTC, Pbruun commented on src/components/common/timeSearch/DatePicker.vue
> +								t('error.outofRange'),
Yet to be added. Same for the other CustomErrors regarding the calendar

2025-01-07 09:04 UTC, jesperlauridsen commented on src/components/common/timeSearch/DayPicker.vue
> +			<span class="date-span">Dato:</span>
Needs to be translated

2025-02-07 13:35 UTC, danielqvistcom requested changes
NICE update!  :) 

A little error:
I get an error, if I delete tekst in inputfield - and then click on a date in the calendar. "Anvend" doesn't turn active.

Design-updates:
Maybe a little less white-space left/right in the inputfield. From left/right-border to tekst.

(All over :hover = #C4F1ED)
**Hover on "active date" - should just stay blue.**
(dp__active_date:hover)

"Anvend" - in it's "correct result state" needs our "Foward/approve-green" = #49da87

When month/year-menu open:
Bottom icon (call) - change to: X-icon+ "Luk måned"/"Luk år" if possible. Else just "Luk".
Same with hover-color.

Har forsøgt at illustrere det hele her (nederst):
https://kb-dk.atlassian.net/wiki/spaces/DRAR/pages/13829699/Filtrering

2025-02-27 08:59 UTC, jesperlauridsen commented
> Nice job! 👍 All fixed and rdy to fly! :) I'll ask UX/Content for input on error messages.

Does this mean you want me to put it on hold untill UX gets back with how they want the error messages worded, or does this mean we run with what we got for now, and then we can update them later - since you've approved it?

2025-02-27 11:37 UTC, Pbruun commented on src/components/common/timeSearch/DayPicker.vue
> +			format: 'd-M-yyy',
Shouldn't it be dd-MM-yyyy ?

2025-02-27 11:50 UTC, Pbruun commented on src/components/common/timeSearch/DayPicker.vue
> +			format: 'd-M-yyy',
Ohh I see the interaction in the datepicker we keep the month and day to one number if possible. I'm just not used to seeing yyy in the date format.

2025-02-27 11:51 UTC, danielqvistcom commented
I'll get back, IF there's something to the wording. Then I'll create new "bug"-task for the updates.
So - run with what we got for now, and then we can update them later.

2025-02-27 12:27 UTC, jesperlauridsen commented on src/components/common/timeSearch/DayPicker.vue
> +			format: 'd-M-yyy',
That should be yyyy, good catch!

2025-02-27 13:07 UTC, Pbruun commented on src/components/common/timeSearch/DatePicker.vue
>  			//endDatePicker.value ? endDatePicker.value.updateInternalModelValue(endDate.value) : null;
Commented out code

2025-02-28 00:20 UTC, jesperlauridsen commented on src/components/common/timeSearch/DatePicker.vue
>  			//endDatePicker.value ? endDatePicker.value.updateInternalModelValue(endDate.value) : null;
We'll leave that one for now.

2025-02-28 00:20 UTC, jesperlauridsen commented on src/components/common/timeSearch/DatePicker.vue
>  			//startDatePicker.value ? startDatePicker.value.updateInternalModelValue(startDate.value) : null;
We'll leave that one for now.

2025-03-03 13:19 UTC, Pbruun commented on src/components/search/CurrentFilters.vue
> +				}
if else, return true or false is kinda redundant.

2025-03-03 13:45 UTC, Pbruun commented on src/components/common/timeSearch/DayPicker.vue
> +						`startTime:[${singleDayStartDate.value.toISOString() + ' TO ' + singleDayEndDate.value.toISOString()}]`,
Seems a bit odd to string concatenate while using template literals.

2025-03-03 13:55 UTC, Pbruun commented on src/components/common/timeSearch/DatePicker.vue
> +				timeSearchStore.setFilterSearchReady(false);
Man kunne i stedet for if else: timeSearchStore.setFilterSearchRead(validEndDate.value && validStartDate.value)

2025-03-03 14:06 UTC, Pbruun commented on src/components/common/timeSearch/DayPicker.vue
> +						`startTime:[${singleDayStartDate.value.toISOString() + ' TO ' + singleDayEndDate.value.toISOString()}]`,
I would write: `startTime:[${singleDayStartDate.value.toISOString()} TO ${singleDayEndDate.value.toISOString()}]`

2025-03-03 14:10 UTC, Pbruun commented on src/components/search/CurrentFilters.vue
> +				}
const filtersActive = computed(() => {
			if (
				startDate.value !== null &&
				(startDate.value as unknown as string) !== '' &&
				endDate.value !== null &&
				(endDate.value as unknown as string) !== ''
			) {
				return (
					(days.value.filter((entity: SelectorData) => entity.selected === true).length > 0 ||
						months.value.filter((entity: SelectorData) => entity.selected === true).length > 0 ||
						timeslots.value.filter((entity: SelectorData) => entity.selected === true).length > 0 ||
						searchResultStore.categoryFilters.length !== 0 ||
						searchResultStore.channelFilters.length !== 0 ||
						startDate.value.getTime() !== startYear.value.getTime() ||
						endDate.value.getTime() !== endYear.value.getTime() ||
						searchResultStore.preliminaryFilter !== '') &&
					!timeSearchStore.newSearchReqMet
				);
			} else {
				return false;
			}
		});

Thinking something like this instead. 
But then again, the other code makes it more readable what is expected from the code.

2025-03-03 14:37 UTC, jesperlauridsen commented on src/components/common/timeSearch/DayPicker.vue
> +						`startTime:[${singleDayStartDate.value.toISOString() + ' TO ' + singleDayEndDate.value.toISOString()}]`,
Yea, this seems kinda... stupid. Will fix!

2025-03-06 12:50 UTC, Pbruun commented
This looks great, I'm happy! :)

2025-03-06 12:50 UTC, merged