Disc 118/global error handling
kb-dk/ds-web pull request #43
Opened 2023-09-06 12:50 UTC by jorntx

This took a really long time and quite a few iterations. Take a look at it and then let's talk about if this is the right approach.

I built a simple error-manager (which can be tuned to our needs) and I injected it globally in the app through Vues provider hooks. 

I tapped into request/response Axios interceptors for future use - they are not ciritical for the core of the error-manager right now.

2023-09-07 11:38 UTC, jesperlauridsen commented on src/error-handling/ErrorManagerType.ts
> +import { AxiosError } from 'axios';
This type should probably be moved to live with the other types we have in the project ;-)

2023-09-07 11:40 UTC, jesperlauridsen commented on src/error-handling/error-manager.ts
> +			// Remove error after 5 seconds
Curious why this is needed. When the error is published, could we not just remove it right away? Whats the reason for the 5 second delay? Alternativly - should the notification module instead submit an event when the error has been displayed to remove it?

2023-09-07 11:41 UTC, jesperlauridsen commented on src/store/searchResults.ts
> -	id: 'searchResults',
The id is gone in the new way the store is made - Is this an oversight, or are we just not using it for anything?

2023-09-07 11:42 UTC, jesperlauridsen requested changes
This looks very solid - and super cool. I think it's a very good foundation for the notification/error system for the app.

I've asked a few questions in the comments - move the types and we're all good to merge! ;)

Good job!

2023-09-07 12:22 UTC, jorntx commented on src/error-handling/ErrorManagerType.ts
> +import { AxiosError } from 'axios';
Yes, totally agree and you supplied good arguments:)

2023-09-07 12:29 UTC, jorntx commented on src/error-handling/error-manager.ts
> +			// Remove error after 5 seconds
Only to suppress the scenario that the _exact same_ error is submitted several times within a very short time frame. I don't think that multiple events of the exact same kind (within a short time frame - e.g. 3 seconds) are necessary to dispatch to the user.

I have no hook for call backs from the notifier so I think if the error-notification should be suppressed or removed internally in the error-manager it should be by some internal metric.

In regards to keeping the notifications relevant and dismissing them I will confidently outsource this to the notifier.

2023-09-07 12:30 UTC, jorntx commented on src/store/searchResults.ts
> -	id: 'searchResults',
It's definitely an oversight (good catch) and frankly I don't now if we use it all. To me the app functions as normal.

2023-09-07 12:33 UTC, jorntx commented
Types moved as requested

2023-09-11 08:36 UTC, jesperlauridsen approved these changes
I think this is an excellent foundation for the error handling. Well done!

2023-09-11 08:36 UTC, merged