Disc 183/persist chosen locale
kb-dk/ds-web pull request #61
Opened 2023-10-13 05:45 UTC by jorntx

First stab at persisting locale. I choose a combo between url and localstorage so we don't have to carry the url-param around on every single page but still maintaining the possibility to link/bootstrap the app in a certain locale.

Note DISC-303 (not coded yet) will complete the functionality by spreading this approach app wide. 

So see if you like where this is heading and then I will carry on with DISC-303 in a separate PR

2023-10-13 10:09 UTC, jorntx commented
Just merged a rather bulky main into this branch

2023-10-18 11:51 UTC, jesperlauridsen commented on src/App.vue
> +					locale: currentLocale.value,
This would remove any actual query that had been done, and push you to the frontpage without a query set. Is this intentional?

2023-10-18 12:03 UTC, jesperlauridsen requested changes
Took it for a spin. The local store wrapper seems to work nicely, The only problem I have right now is that changing the language seems to reset everything done before it. Imho that should not be the case - Hopefully you agree and it's fixable :-) Otherwise we'll have a discussion about it!

2023-10-25 07:56 UTC, jorntx commented on src/App.vue
> +					locale: currentLocale.value,
No! And thanks for spotting this - this is a boboo on my part and I have comitted a fix.

2023-10-26 12:00 UTC, jesperlauridsen commented
Very noice! I'll accept it and make little bug report for the small issue I found!

2023-10-26 12:00 UTC, jesperlauridsen approved these changes

2023-10-26 12:00 UTC, merged