Disc 321/pagination first step
kb-dk/ds-web pull request #74
Opened 2023-11-03 12:43 UTC by jorntx

Finally got a little time to attend to this:)

I took a look at some plugins and other implementations and I created a very stripped down version of a pager. 

I made this a draft as there is no styling and the pager is not hooked up to the api. This is just to test if the pager-mechanism itself works and is what we are aiming for. 

For the reference the pager plugin I looked at was 75.6kb uncompressed. This code is now 7kb uncompressed, so if it does the trick (and even with styling and hooks) it has saved some bandwidth:)

Ohhh and don't worry - the beefee comments will be removed once you have looked it over.

2023-11-08 13:51 UTC, jorntx commented
Is we talked this is bumped from draft to PR and I added functionality for updated the URL and then we will hook this up to the API later as well as add styling.

I also made an init method in the pager to bootstrap the correct state on reload or direct linking

2023-11-09 09:46 UTC, jesperlauridsen commented on src/components/search/Pager.vue
> +			Previous
Translations :D

2023-11-09 09:46 UTC, jesperlauridsen commented on src/components/search/Pager.vue
> +			Next
Translations! :D

2023-11-09 10:00 UTC, jesperlauridsen requested changes
I think this looks very, very nice! Only thing missing is translations on the buttons.

Also, just a little note to us - when doing a new search, start should be set to 0 again. Right now it doesn't, but that's fine since it's not hooked up yet. We just need to remember to do that :)

2023-11-09 12:31 UTC, jesperlauridsen commented on src/components/search/Pager.vue
> +				&gt;
Im sorry to be an ass here - but I think, from the design perspective, that we need to use the material icons for the arrows. Like such:

	<i class="material-icons " aria-hidden="true">chevron_right</i>
	
	with chevron_left and chevron_right instead, they fit the design better.

2023-11-09 12:31 UTC, jesperlauridsen commented on src/components/search/Pager.vue
> +			>
Im sorry to be an ass here - but I think, from the design perspective, that we need to use the material icons for the arrows. Like such:

	<i class="material-icons " aria-hidden="true">chevron_right</i>
	
	with chevron_left and chevron_right instead, they fit the design better.

2023-11-09 12:35 UTC, jorntx commented
Thanks - material icons added

2023-11-09 12:59 UTC, jesperlauridsen approved these changes
Very nice!

2023-11-09 13:12 UTC, merged