First pass at basic audio record
kb-dk/ds-web pull request #94
Opened 2023-11-21 09:29 UTC by jorntx

Basic view of audio record.

Ignore the video player stuff this will be fixed in separate ticket/PR

2023-11-22 10:33 UTC, jesperlauridsen commented on src/components/records/BroadcastAudioRecord.vue
> +					:title="t('record.moreMetadataBroadcast')"
This change should probably also be in the BroadcastVideoRecord. Also, if we want reactivity, we might want to watch the locale and make a re-render when the language is changed - that doesn't happen right now.

2023-11-22 10:33 UTC, jesperlauridsen requested changes
I just left a little comment. The translation on the title in the accordian should probably also be in the Video template one - and then a little question about the reactivity.

2023-11-23 09:04 UTC, jorntx commented on src/components/records/BroadcastAudioRecord.vue
> +					:title="t('record.moreMetadataBroadcast')"
Agreed

2023-11-23 09:05 UTC, jorntx commented on src/components/records/BroadcastAudioRecord.vue
> +					:title="t('record.moreMetadataBroadcast')"
As we just talked about - lets take a stern look at out locale handling/reactivity in a separate ticket.

2023-11-27 08:39 UTC, jesperlauridsen approved these changes

2023-11-27 08:39 UTC, merged